language: ruby
rvm:
- 2.2.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: kjaermaxi.me
  apt:
    packages:
      - graphicsmagick
before_install:
- bash _scripts/install.sh
script:
- bash _scripts/build.sh
- bash _scripts/test.sh
after_success:
- bash _scripts/deploy.sh
